name: "YOUR WORK FLOW NAME"

# Configure which branch that will trigger Eggplant DAI GitHub Action
on:
  push:
    branches:
      - Suites 
  pull_request:
     branches:
      - Suites

jobs:
  Run-DAI-Test-Configuration:
    strategy: # Optional configuration by using matrix strategy
      max-parallel: 1 # To set the maximum number of jobs that can run simultaneously 
    runs-on: [self-hosted,windows] # Provide OS matrix
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.16
        with:
          serverURL: "http://localhost:8000/" # Required. Details below
          testConfigID: "35826c55-f499-4229-a03e-bb53a37f8379" # Required. Details below
          clientID: "client:dai:api:integration:29ed6fbc-74c2-4992-8a93-1d035a2b0852" # Required. Details below
          clientSecret: "yPaK7yzQtt5uacXoTZBccpb40EfBtqRX" # Required. Details below
